
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";
import LayoutWrapper from "@/component/LayoutWrapper";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const shabnam = localFont({
    src: [
        {
            path: "../assets/fonts/shabnam/Farsi-Digits-Without-Latin/Shabnam-Bold-FD-WOL.woff2",
            weight: "700",
            style: "normal",
        },
    ],
    variable: "--font-shabnam",
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {

    return (
        <html lang="en">
            <body className={shabnam.className}>
                <Providers>
                    <LayoutWrapper>
                        {children}
                    </LayoutWrapper>
                </Providers>
            </body>
        </html>
    );
}
