import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/component/header/page";
import Footer from "@/component/footer/page";
import { ReserveProvider } from "@/core/context/ReserveContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const shabnam = localFont({
  src: [
    {
      path: "../assets/fonts/shabnam/Farsi-Digits-Without-Latin/Shabnam-Bold-FD-WOL.woff2", // ✅ Use modern format
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-shabnam",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={shabnam.className}>
        <header><Header /></header>
        <ReserveProvider>
          {children}
        </ReserveProvider>

        <footer><Footer /></footer>
      </body>
    </html>
  );
}